#! /bin/sh
# Reference from sawatchdog of CentOS
# Start the RMM watchdog daemon
#
### BEGIN INIT INFO
# Provides: sawatchdog
# Required-Start: 
# Required-Stop: 
# Default-Start:  3 4 5
# Default-Stop:   0 1 2 6
# Short-Description: RMM watchdog server
# Description:    RMM watchdog server
### END INIT INFO
# Return values acc. to LSB for all commands but status:
# 0       - success
# 1       - generic or unspecified error
# 2       - invalid or excess argument(s)
# 3       - unimplemented feature (e.g. "reload")
# 4       - user had insufficient privileges
# 5       - program is not installed
# 6       - program is not configured
# 7       - program is not running
# 8--199  - reserved (8--99 LSB, 100--149 distrib, 150--199 appl)
# 
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signaling is not supported) are
# considered a success.

# be extra carefull cause connection fail if TMPDIR is not writeable
export TMPDIR="/cache"

. /etc/init.d/functions

SAAGENT_DIR="/usr/local/AgentService/"
SAAGENT_BIN="${SAAGENT_DIR}sawatchdog"
SAAGENT_CONF="${SAAGENT_DIR}SAWatchdog_Config"
SAAGENT_PID="/var/run/SAWatchdog.pid"
SAAGENT_LOCK="/var/lock/subsys/sawatchdog"
SAAGENT_LOG="/var/log/sawatchdog.log"

RETVAL=0

#Override Function
getpid() {
	if [ -n "`command -v pidof`" ]; then
        	pid=`pidof $1`
        elif [ -n "`command -v pidofproc`" ]; then
        	pid=`pidofproc $1`
        else
		pid=0
        	echo "Failed read PID."
        fi
}

killproc() { # kill the named process(es)
        if [ -n "`command -v pidof`" ]; then
        	pid=`pidof $1` && kill -s 9 $pid
        elif [ -n "`command -v pidofproc`" ]; then
        	pid=`pidofproc $1` && kill -s 9 $pid
        else
        	echo "Failed read PID."
        fi
}

# Check for missing binary
if [ ! -x ${SAAGENT_BIN} ]; then
	echo -n 1>&2 "RMM watchdog daemon, ${SAAGENT_BIN} is not installed."
	echo 
	exit 5
fi

case "$1" in
	start)
		#check configure file
		if [ ! -f ${SAAGENT_CONF} ]; then
			echo -n >&2 "RMM watchdog configuration file, ${SAAGENT_CONF} does not exist. "
			exit 6
		fi
		#action
		if [ -f ${SAAGENT_LOCK} ]; then						
			echo -n "RMM watchdog daemon already running."
			echo 
			exit 1
		else 
			echo -n "Starting RMM watchdog daemon..."
			##daemon "${SAAGENT_BIN}"
			cd ${SAAGENT_DIR}
			# jinxin mask
			#./sawatchdog >/dev/null 2>&1 &		
			RETVAL=0
			[ $RETVAL -eq 0 ] && touch ${SAAGENT_LOCK}
			echo
		fi
		;;
		
	stop)
		#check service status
		if [ -f ${SAAGENT_LOCK} ]; then
			echo -n "Shutting down RMM watchdog daemon..."		
			#getpid "${SAAGENT_BIN}"	
			#if [ "${pid}" = "0" ]; then
			#	RETVAL=0
			#elif [ -z "${pid}" ]; then
			#	RETVAL=0
			#else
			#	killproc "${SAAGENT_BIN}"		
			#	RETVAL=$?
			#fi
			RETVAL=0
			[ $RETVAL -eq 0 ] && rm -f ${SAAGENT_LOCK}
			[ $RETVAL -eq 0 ] && rm -f ${SAAGENT_PID}
			echo
		else
			echo -n "RMM Agent daemon is not running."
			echo 
			exit 1
		fi
		;;		

	restart)
		$0 stop
		$0 start
		;;

	status)
		status sawatchdog
        RETVAL=$?
		;;
		
	condrestart)
		if [ -f ${SAAGENT_LOCK} ]; then
			$0 restart
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart|condrestart}"
		exit 1
		;;
esac
exit $RETVAL

