#!/bin/sh

# Source function library.
. /etc/init.d/functions

case "$1" in
    start)
        echo -n "Starting Boot Times: "
        export DISPLAY=:0
        /tools/boottimes.sh
        echo "OK"
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac

exit 0
