#!/bin/sh
#
test -f /usr/sbin/mosquitto || exit 0
test -f /etc/mosquitto/conf.d || exit 0
case "$1" in
	start )
		echo -n "Starting MQTT Server: "
		/usr/sbin/mosquitto -c /etc/mosquitto/conf.d -d  > /dev/null 2>&1 &
        if [ "$?" = "0" ]; then
		    echo " [ OK ]"
		else
		    echo " [ Fail ]"
		fi
		;;
	stop )
		echo -n "Stopping MQTT Server: "
		kill -s 9 `pidof mosquitto` > /dev/null 2>&1
		sleep 2
		tr=`ps aux | grep 'mosquitto' | grep -v grep`
		if [ "x$tr" = "x" ]; then
		    echo " [ OK ]"
		else
		    echo " [ Fail ]"
		fi
		;;
	restart )
		$0 stop
		sleep 2
		$0 start
		if [ "$?" != "0" ]; then
			exit 1
		fi
		;;
	*)
		echo "Usage: /etc/init.d/mqtt {start|stop|restart}"
		exit 1 
esac

exit 0
