#!/bin/sh

MCCED_BIN=/usr/bin/edge-core
MCCED_PARAMS="-p 22225 -o 8081"

# Source function library.
. /etc/init.d/functions

case "$1" in
    start)
        echo -n "Starting Mbed edge: "
        (start-stop-daemon --start --exec $MCCED_BIN -- $MCCED_PARAMS -pidfile /var/run | logger -t mbed) &
        echo "OK"
        ;;
    stop)
        echo -n "Stopping Mbed edge: "
        start-stop-daemon --stop --signal 3 --quiet --exec $MCCED_BIN
        echo "OK"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
