#!/bin/sh

# confrouter - service config router for the Unified Configuration Interface
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# working flow:
#    uci commit <PACKAGE NAME> ---> /etc/ucisa/confrouter
#                                         |
#          router to each package's handler
#                                         |
#          try to read ${CHANGE_LOG} to know updated configuration
#                                         |
#          decide whether need to restart service

PACKAGE_NAME=$1
ROUTER_CONFIG=/etc/ucisa/ucisa.conf
CHANGED_LOG=/tmp/.ucichg/${PACKAGE_NAME}

#0:disable log; 1:enable sys log; other:console
ROUTER_DEBUG=1

salog()
{
    if [ "$ROUTER_DEBUG" = "1" ]; then
        logger -t "ucisa" "$1";
    else
        if [ "$ROUTER_DEBUG" = "0" ]; then
            op=do_none
        else
            echo "$1"
        fi
    fi
}

salog "config router runs for ${PACKAGE_NAME}."
entry=`grep -m 1 ${PACKAGE_NAME} ${ROUTER_CONFIG}`
handler=`echo $entry | sed 's/ //g' | awk -F= {'print $2'}`
#If the service handler is time consuming, it is better to make it work
#on background.
if [ -z $handler ]; then
    salog "no service handler found for ${PACKAGE_NAME}."
    exit 1;
fi
salog "config router to $handler."
`${handler} stop > /dev/null 2>&1`
sleep 2s
`${handler} start > /dev/null 2>&1`
exit $?
